### ISSUE TITLE
Some wiki in Basics

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#36]
How to flash Raspberry?
How to use Arduino?
And other devices?

I suggest to add main tutorial in Baiscs (or in any-other-category you desire). Maybe, you can use a structure like this (link [here](https://github.com/RIOT-OS/RIOT/wiki))

![image](https://cloud.githubusercontent.com/assets/676052/23889512/d79def30-088d-11e7-9a16-ce841415ee52.png)

**Comment by giowild** [comment]
Not sure to understand exactly... Can you create it directly?

You can create a new Index2 page, or also modify the existing index, so we
can approve changes or revert back to old revision... or also comment this
issue with the markdown code

Please comment on this issue when it is ready.

Thanks!

Il 14/mar/2017 08:13, "Andrea Rossi" <notifications@github.com> ha scritto:

**Comment by giowild** [comment]
I also think that between all tutorials, arduino and raspberry ones are not
so easy for beginners, because they need to flash arduino and rasp images
which means installing other tools and expertise...

The easiest tutorials imho are Nano and Flic buttons and eventually also
beacons

Il 14/mar/2017 09:20, "Giovanni Lenzi" <g.lenzi@smileupps.com> ha scritto:

**Comment by giowild** [comment]
Please open this again if the issue is still not solved.
