### ISSUE TITLE
"Using Beacons in SAndroidE" tutorial

### ISSUE THREAD

**Issue by PiccoliPaolo93** [SAndroidEOfficial/framework#38]
There are two little problems in that tutorial.
One is about the ListView logList.
At the instruction 3.4 there is the definition `private ListView mLogList;` 
At 3.7 `mLogList=(ListView) findViewById(R.id.logList);`
But there isn't a instruction about creating that ListView in the associated .xml file

The other one is about a warning.
At 6 there is this instruction `logLines.add(0,String.format("%s %s",new Date().getSeconds(),s));`
`Date().getSeconds()` is Deprecated and is suggested to use `Calendar.get(Calendar.SECOND)`
[https://developer.android.com/reference/java/util/Date.html](url)

**Comment by giowild** [comment]
Ok, thanks for feedback, just improved the tutorial: 

* added loglist together with button in xml of the tutorial
* used Calendar instead of Date
* added nearable message parsing to show how to get temperature and accell values from nearable beacons
* added note to turn on gps, if no beacons are displayed
