### ISSUE TITLE
[BLENano] Some trouble about pin and Digital Input

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#39]
Hi guys, me and my colleague @koldar (https://github.com/Koldar) we are working on BLE tutorial and we make this circuit

![img_20170327_102921](https://cloud.githubusercontent.com/assets/676052/24347463/b76c33a2-12d8-11e7-9dd3-c900741b3fad.jpg)

We try many times with different pid (8,9,10,11) but nothing happens.

In the end, we try to change from Digital Input to Analog Input and use pin 5 and we can see some change.

So, why doesn't digital input work?

**Comment by giowild** [comment]
Hi!

You are right, firmware provided in tutorial was lacking pins 8,9,10,11 because they were reserved for serial communication. However, I just added them as digital pins too, so you are free to use them for serial communication or as digital pin as well.

Just download the new firmware from [https://raw.githubusercontent.com/SAndroidEOfficial/sandroide-redbear-nano/master/BLE_RedBearNano-SAndroidE.hex](https://raw.githubusercontent.com/SAndroidEOfficial/sandroide-redbear-nano/master/BLE_RedBearNano-SAndroidE.hex) and try again your sandroide application.

Please, close this ticket if it works as expected.
